name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sql-server:
        image: mcr.microsoft.com/mssql/server
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MSSQL_PID: Express
        ports:
          - '1433:1433'

    env:
      DB_HOST: localhost
      DB_PORT: 1433
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      JWT_KEY: ${{ secrets.JWT_KEY }}
      DB_DIALECT: mssql

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to database
        run: sqlcmd -U $DB_USER -P $DB_PASSWORD -S $DB_HOST,$DB_PORT -Q "CREATE DATABASE $DB_NAME;"

      - name: Set up environment variables
        run: |
          echo "DB_HOST=${DB_HOST}" >> $GITHUB_ENV
          echo "DB_PORT=${DB_PORT}" >> $GITHUB_ENV
          echo "DB_USER=${DB_USER}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${DB_PASSWORD}" >> $GITHUB_ENV
          echo "DB_NAME=${DB_NAME}" >> $GITHUB_ENV
          echo "JWT_KEY=${JWT_KEY}" >> $GITHUB_ENV
          echo "DB_DIALECT=${DB_DIALECT}" >> $GITHUB_ENV

      - name: Install dockerize
        run: |
          wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz
          tar -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
          sudo mv dockerize /usr/local/bin/dockerize
          rm dockerize-linux-amd64-v0.6.1.tar.gz

      - name: Install sequelize-cli
        run: npm install -g sequelize-cli

      - name: Wait for SQL Server to be ready
        run: dockerize -wait tcp://${DB_HOST}:${DB_PORT} -timeout 1m

      - name: Install dependencies
        run: npm install

      - name: Run Sequelize migrations
        run: npx sequelize-cli db:migrate --env actions
      
      - name: Run tests
        run: npm test